/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_ObjectDetection */

#ifndef _Included_org_cripac_isee_ObjectDetection
#define _Included_org_cripac_isee_ObjectDetection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cripac_isee_ObjectDetection
 * Method:    loadLibrary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_ObjectDetection_loadLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cripac_isee_ObjectDetection
 * Method:    initialize
 * Signature: (JILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_ObjectDetection_initialize
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     org_cripac_isee_ObjectDetection
 * Method:    detect
 * Signature: (J[BIII[F[F)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_ObjectDetection_detect
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jint, jfloatArray, jfloatArray);

/*
 * Class:     org_cripac_isee_ObjectDetection
 * Method:    release
 * Signature: (J)II
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_ObjectDetection_release
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cripac_isee_ObjectDetection
 * Method:    closeLibrary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_ObjectDetection_closeLibrary
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
